# Generated by Django 3.2 on 2021-04-22 12:27

from django.db import migrations, models
import places.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTags',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResourcesRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(null=True)),
                ('contact', models.CharField(max_length=256)),
                ('location', places.fields.PlacesField(max_length=255)),
                ('resolved', models.BooleanField(default=False)),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')])),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='core.CategoryTags')),
            ],
        ),
        migrations.CreateModel(
            name='ResourcesPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True)),
                ('last_update_on', models.DateTimeField(auto_now_add=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('location', places.fields.PlacesField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contacts', models.TextField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('tags', models.ManyToManyField(to='core.CategoryTags')),
            ],
        ),
    ]
