# Generated by Django 3.2 on 2021-04-22 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcespost',
            name='last_update_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
