# Generated by Django 3.2 on 2021-04-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_resourcespost_last_update_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcespost',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='resourcesrequest',
            name='description',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
